### ISSUE TITLE
Improved WASM support

### ISSUE THREAD

**Issue by nathanielsimard** [tracel-ai/burn#1256]
This is a meta-issue that tracks progress on better supporting wasm with the framework.

Most of these issues should be resolved in the order listed below:

- [ ] [burn-common] add web workers support #1250
- [ ] [burn-wgpu] refactor wgpu compute server to use web worker #1251
- [ ] [burn-tensor] remove the async API when reading tensor #1252
- [ ] Refactor threads into async tasks #1253
- [ ] [burn-train] wasm support #1254
- [ ] [example] training on a wasm runtime #1255

**Comment by antimora** [comment]
Most of the items are completed; Will reopen once we have a specific issue.
