### ISSUE TITLE
FaceONNX models import issues tracker

### ISSUE THREAD

**Issue by SimonBrandner** [tracel-ai/burn#2116]
This is a tracker issue for problems with importing models from: https://github.com/FaceONNX/FaceONNX

I've made a test repo for this purpose: https://github.com/SimonBrandner/burn-import-testbed

- [x] eye_blink_classifier
- [x] recognizer
- [ ] detector: almost done (see https://github.com/tracel-ai/burn/issues/1915)
- [ ] depth_classifier: https://github.com/tracel-ai/burn/issues/2111
- [ ] landmarks_detector: https://github.com/tracel-ai/burn/issues/2115
- [ ] yolov5s-detector: https://github.com/tracel-ai/burn/issues/2058

**Comment by antimora** [comment]
Closing this umbrella tracker in favor of https://github.com/tracel-ai/burn-onnx/issues/18.

If you come across more issue, lets open a specific issue. A lot has changed since this ticket was opened.
